// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("sendgrid");

export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey") ?? utilities.getEnv("SENDGRID_API_KEY");
    },
    enumerable: true,
});

export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host") ?? utilities.getEnv("SENDGRID_HOST");
    },
    enumerable: true,
});

export declare const subuser: string | undefined;
Object.defineProperty(exports, "subuser", {
    get() {
        return __config.get("subuser") ?? utilities.getEnv("SENDGRID_SUBUSER");
    },
    enumerable: true,
});

