// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainAuthenticationDn {
    /**
     * The actual DNS record.
     */
    data?: pulumi.Input<string | undefined>;
    /**
     * The domain that this CNAME is created for.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * The type of DNS record.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Indicates if this is a valid CNAME.
     */
    valid?: pulumi.Input<boolean | undefined>;
}

export interface LinkBrandingDn {
    /**
     * The actual DNS record.
     */
    data?: pulumi.Input<string | undefined>;
    /**
     * The domain that this CNAME is created for.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * The type of DNS record.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Indicates if this is a valid CNAME.
     */
    valid?: pulumi.Input<boolean | undefined>;
}

export interface WebhookSecurityPolicyOauth {
    /**
     * The OAuth client ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * The OAuth client secret. This value is sensitive and will not be displayed in logs.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * List of OAuth scopes required for webhook access.
     */
    scopes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The OAuth token URL.
     */
    tokenUrl: pulumi.Input<string>;
}

export interface WebhookSecurityPolicySignature {
    /**
     * Whether signature verification is enabled for this webhook security policy.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The public key used for signature verification. This is computed by SendGrid when signature is enabled.
     */
    publicKey?: pulumi.Input<string | undefined>;
}
