// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainAuthenticationDn {
    /**
     * The actual DNS record.
     */
    data: string;
    /**
     * The domain that this CNAME is created for.
     */
    host: string;
    /**
     * The type of DNS record.
     */
    type: string;
    /**
     * Indicates if this is a valid CNAME.
     */
    valid: boolean;
}

export interface LinkBrandingDn {
    /**
     * The actual DNS record.
     */
    data: string;
    /**
     * The domain that this CNAME is created for.
     */
    host: string;
    /**
     * The type of DNS record.
     */
    type: string;
    /**
     * Indicates if this is a valid CNAME.
     */
    valid: boolean;
}

export interface WebhookSecurityPolicyOauth {
    /**
     * The OAuth client ID.
     */
    clientId: string;
    /**
     * The OAuth client secret. This value is sensitive and will not be displayed in logs.
     */
    clientSecret: string;
    /**
     * List of OAuth scopes required for webhook access.
     */
    scopes: string[];
    /**
     * The OAuth token URL.
     */
    tokenUrl: string;
}

export interface WebhookSecurityPolicySignature {
    /**
     * Whether signature verification is enabled for this webhook security policy.
     */
    enabled: boolean;
    /**
     * The public key used for signature verification. This is computed by SendGrid when signature is enabled.
     */
    publicKey: string;
}

