// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiKey extends pulumi.CustomResource {
    /**
     * Get an existing ApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiKeyState, opts?: pulumi.CustomResourceOptions): ApiKey {
        return new ApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/apiKey:ApiKey';

    /**
     * Returns true if the given object is an instance of ApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiKey.__pulumiType;
    }

    /**
     * The API key created by the API.
     */
    declare public /*out*/ readonly apiKey: pulumi.Output<string>;
    /**
     * The name you will use to describe this API Key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The individual permissions that you are giving to this API Key.
     */
    declare public readonly scopes: pulumi.Output<string[]>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    declare public readonly subUserOnBehalfOf: pulumi.Output<string | undefined>;

    /**
     * Create a ApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiKeyArgs | ApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiKeyState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["name"] = state?.name;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["subUserOnBehalfOf"] = state?.subUserOnBehalfOf;
        } else {
            const args = argsOrState as ApiKeyArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["subUserOnBehalfOf"] = args?.subUserOnBehalfOf;
            resourceInputs["apiKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ApiKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiKey resources.
 */
export interface ApiKeyState {
    /**
     * The API key created by the API.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * The name you will use to describe this API Key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The individual permissions that you are giving to this API Key.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiKey resource.
 */
export interface ApiKeyArgs {
    /**
     * The name you will use to describe this API Key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The individual permissions that you are giving to this API Key.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
}
