// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class DomainAuthentication extends pulumi.CustomResource {
    /**
     * Get an existing DomainAuthentication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainAuthenticationState, opts?: pulumi.CustomResourceOptions): DomainAuthentication {
        return new DomainAuthentication(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/domainAuthentication:DomainAuthentication';

    /**
     * Returns true if the given object is an instance of DomainAuthentication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainAuthentication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainAuthentication.__pulumiType;
    }

    /**
     * Whether to allow SendGrid to manage your SPF records, DKIM keys, and DKIM key rotation.
     */
    declare public readonly automaticSecurity: pulumi.Output<boolean | undefined>;
    /**
     * Add a custom DKIM selector. Accepts three letters or numbers.
     */
    declare public readonly customDkimSelector: pulumi.Output<string | undefined>;
    /**
     * Specify whether to use a custom SPF or allow SendGrid to manage your SPF. This option is only available to authenticated domains set up for manual security.
     */
    declare public readonly customSpf: pulumi.Output<boolean | undefined>;
    /**
     * The DNS records used to authenticate the sending domain.
     */
    declare public /*out*/ readonly dns: pulumi.Output<outputs.DomainAuthenticationDn[]>;
    /**
     * Domain being authenticated.
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * The IP addresses that will be included in the custom SPF record for this.
     */
    declare public readonly ips: pulumi.Output<string[]>;
    /**
     * Whether to use this authenticated domain as the fallback if no authenticated domains match the sender's domain.
     */
    declare public readonly isDefault: pulumi.Output<boolean | undefined>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    declare public readonly subUserOnBehalfOf: pulumi.Output<string | undefined>;
    /**
     * The subdomain to use for this authenticated domain.
     */
    declare public readonly subdomain: pulumi.Output<string>;
    /**
     * The username associated with this domain.
     */
    declare public /*out*/ readonly username: pulumi.Output<string>;
    /**
     * Indicates if this is a valid authenticated domain or not.
     */
    declare public readonly valid: pulumi.Output<boolean>;

    /**
     * Create a DomainAuthentication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainAuthenticationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainAuthenticationArgs | DomainAuthenticationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainAuthenticationState | undefined;
            resourceInputs["automaticSecurity"] = state?.automaticSecurity;
            resourceInputs["customDkimSelector"] = state?.customDkimSelector;
            resourceInputs["customSpf"] = state?.customSpf;
            resourceInputs["dns"] = state?.dns;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["ips"] = state?.ips;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["subUserOnBehalfOf"] = state?.subUserOnBehalfOf;
            resourceInputs["subdomain"] = state?.subdomain;
            resourceInputs["username"] = state?.username;
            resourceInputs["valid"] = state?.valid;
        } else {
            const args = argsOrState as DomainAuthenticationArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["automaticSecurity"] = args?.automaticSecurity;
            resourceInputs["customDkimSelector"] = args?.customDkimSelector;
            resourceInputs["customSpf"] = args?.customSpf;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["ips"] = args?.ips;
            resourceInputs["isDefault"] = args?.isDefault;
            resourceInputs["subUserOnBehalfOf"] = args?.subUserOnBehalfOf;
            resourceInputs["subdomain"] = args?.subdomain;
            resourceInputs["valid"] = args?.valid;
            resourceInputs["dns"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DomainAuthentication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DomainAuthentication resources.
 */
export interface DomainAuthenticationState {
    /**
     * Whether to allow SendGrid to manage your SPF records, DKIM keys, and DKIM key rotation.
     */
    automaticSecurity?: pulumi.Input<boolean | undefined>;
    /**
     * Add a custom DKIM selector. Accepts three letters or numbers.
     */
    customDkimSelector?: pulumi.Input<string | undefined>;
    /**
     * Specify whether to use a custom SPF or allow SendGrid to manage your SPF. This option is only available to authenticated domains set up for manual security.
     */
    customSpf?: pulumi.Input<boolean | undefined>;
    /**
     * The DNS records used to authenticate the sending domain.
     */
    dns?: pulumi.Input<pulumi.Input<inputs.DomainAuthenticationDn>[] | undefined>;
    /**
     * Domain being authenticated.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * The IP addresses that will be included in the custom SPF record for this.
     */
    ips?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to use this authenticated domain as the fallback if no authenticated domains match the sender's domain.
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * The subdomain to use for this authenticated domain.
     */
    subdomain?: pulumi.Input<string | undefined>;
    /**
     * The username associated with this domain.
     */
    username?: pulumi.Input<string | undefined>;
    /**
     * Indicates if this is a valid authenticated domain or not.
     */
    valid?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a DomainAuthentication resource.
 */
export interface DomainAuthenticationArgs {
    /**
     * Whether to allow SendGrid to manage your SPF records, DKIM keys, and DKIM key rotation.
     */
    automaticSecurity?: pulumi.Input<boolean | undefined>;
    /**
     * Add a custom DKIM selector. Accepts three letters or numbers.
     */
    customDkimSelector?: pulumi.Input<string | undefined>;
    /**
     * Specify whether to use a custom SPF or allow SendGrid to manage your SPF. This option is only available to authenticated domains set up for manual security.
     */
    customSpf?: pulumi.Input<boolean | undefined>;
    /**
     * Domain being authenticated.
     */
    domain: pulumi.Input<string>;
    /**
     * The IP addresses that will be included in the custom SPF record for this.
     */
    ips?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to use this authenticated domain as the fallback if no authenticated domains match the sender's domain.
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The subuser's username. The API call is made on behalf of the subuser account.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * The subdomain to use for this authenticated domain.
     */
    subdomain?: pulumi.Input<string | undefined>;
    /**
     * Indicates if this is a valid authenticated domain or not.
     */
    valid?: pulumi.Input<boolean | undefined>;
}
