// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DomainAuthenticationValidation extends pulumi.CustomResource {
    /**
     * Get an existing DomainAuthenticationValidation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainAuthenticationValidationState, opts?: pulumi.CustomResourceOptions): DomainAuthenticationValidation {
        return new DomainAuthenticationValidation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/domainAuthenticationValidation:DomainAuthenticationValidation';

    /**
     * Returns true if the given object is an instance of DomainAuthenticationValidation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainAuthenticationValidation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainAuthenticationValidation.__pulumiType;
    }

    /**
     * Id of the domain authentication to validate.
     */
    declare public readonly domainAuthenticationId: pulumi.Output<string>;
    /**
     * The subuser username for on-behalf-of API calls.
     */
    declare public readonly subUserOnBehalfOf: pulumi.Output<string | undefined>;
    /**
     * Indicates if this is a valid authenticated domain or not.
     */
    declare public /*out*/ readonly valid: pulumi.Output<boolean>;

    /**
     * Create a DomainAuthenticationValidation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainAuthenticationValidationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainAuthenticationValidationArgs | DomainAuthenticationValidationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainAuthenticationValidationState | undefined;
            resourceInputs["domainAuthenticationId"] = state?.domainAuthenticationId;
            resourceInputs["subUserOnBehalfOf"] = state?.subUserOnBehalfOf;
            resourceInputs["valid"] = state?.valid;
        } else {
            const args = argsOrState as DomainAuthenticationValidationArgs | undefined;
            if (args?.domainAuthenticationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'domainAuthenticationId'");
            }
            resourceInputs["domainAuthenticationId"] = args?.domainAuthenticationId;
            resourceInputs["subUserOnBehalfOf"] = args?.subUserOnBehalfOf;
            resourceInputs["valid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DomainAuthenticationValidation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DomainAuthenticationValidation resources.
 */
export interface DomainAuthenticationValidationState {
    /**
     * Id of the domain authentication to validate.
     */
    domainAuthenticationId?: pulumi.Input<string | undefined>;
    /**
     * The subuser username for on-behalf-of API calls.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * Indicates if this is a valid authenticated domain or not.
     */
    valid?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a DomainAuthenticationValidation resource.
 */
export interface DomainAuthenticationValidationArgs {
    /**
     * Id of the domain authentication to validate.
     */
    domainAuthenticationId: pulumi.Input<string>;
    /**
     * The subuser username for on-behalf-of API calls.
     */
    subUserOnBehalfOf?: pulumi.Input<string | undefined>;
}
