// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EventWebhook extends pulumi.CustomResource {
    /**
     * Get an existing EventWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EventWebhookState, opts?: pulumi.CustomResourceOptions): EventWebhook {
        return new EventWebhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/eventWebhook:EventWebhook';

    /**
     * Returns true if the given object is an instance of EventWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventWebhook.__pulumiType;
    }

    /**
     * Receiving server could not or would not accept message.
     */
    declare public readonly bounce: pulumi.Output<boolean | undefined>;
    /**
     * Recipient clicked on a link within the message. You need to enable Click Tracking for getting this type of event.
     */
    declare public readonly click: pulumi.Output<boolean | undefined>;
    /**
     * Recipient's email server temporarily rejected message.
     */
    declare public readonly deferred: pulumi.Output<boolean | undefined>;
    /**
     * Message has been successfully delivered to the receiving server.
     */
    declare public readonly delivered: pulumi.Output<boolean | undefined>;
    /**
     * You may see the following drop reasons: Invalid SMTPAPI header, Spam Content (if spam checker app enabled), Unsubscribed Address, Bounced Address, Spam Reporting Address, Invalid, Recipient List over Package Quota.
     */
    declare public readonly dropped: pulumi.Output<boolean | undefined>;
    /**
     * Indicates if the event webhook is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Friendly name for the webhook to help you identify it.
     */
    declare public readonly friendlyName: pulumi.Output<string | undefined>;
    /**
     * Recipient resubscribes to specific group by updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    declare public readonly groupResubscribe: pulumi.Output<boolean | undefined>;
    /**
     * Recipient unsubscribe from specific group, by either direct link or updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    declare public readonly groupUnsubscribe: pulumi.Output<boolean | undefined>;
    /**
     * The client ID Twilio SendGrid sends to your OAuth server or service provider to generate an OAuth access token.
     */
    declare public readonly oauthClientId: pulumi.Output<string | undefined>;
    /**
     * This secret is needed only once to create an access token. SendGrid will store this secret, allowing you to update your Client ID and Token URL without passing the secret to SendGrid again. When passing data in this field, you must also include the oauthClientId and oauthTokenUrl fields.
     */
    declare public readonly oauthClientSecret: pulumi.Output<string | undefined>;
    /**
     * The URL where Twilio SendGrid sends the Client ID and Client Secret to generate an access token. This should be your OAuth server or service provider. When passing data in this field, you must also include the oauthClientId field.
     */
    declare public readonly oauthTokenUrl: pulumi.Output<string | undefined>;
    /**
     * Recipient has opened the HTML message. You need to enable Open Tracking for getting this type of event.
     */
    declare public readonly open: pulumi.Output<boolean | undefined>;
    /**
     * Message has been received and is ready to be delivered.
     */
    declare public readonly processed: pulumi.Output<boolean | undefined>;
    /**
     * The public key used to sign the event webhook. Only present if 'signed' is true
     */
    declare public /*out*/ readonly publicKey: pulumi.Output<string>;
    /**
     * Should the event webhook use signing?
     */
    declare public readonly signed: pulumi.Output<boolean | undefined>;
    /**
     * Recipient marked a message as spam.
     */
    declare public readonly spamReport: pulumi.Output<boolean | undefined>;
    /**
     * Recipient clicked on message's subscription management link. You need to enable Subscription Tracking for getting this type of event.
     */
    declare public readonly unsubscribe: pulumi.Output<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data events from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be eventd and POSTed to this URL.
     */
    declare public readonly url: pulumi.Output<string>;

    /**
     * Create a EventWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventWebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EventWebhookArgs | EventWebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EventWebhookState | undefined;
            resourceInputs["bounce"] = state?.bounce;
            resourceInputs["click"] = state?.click;
            resourceInputs["deferred"] = state?.deferred;
            resourceInputs["delivered"] = state?.delivered;
            resourceInputs["dropped"] = state?.dropped;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["groupResubscribe"] = state?.groupResubscribe;
            resourceInputs["groupUnsubscribe"] = state?.groupUnsubscribe;
            resourceInputs["oauthClientId"] = state?.oauthClientId;
            resourceInputs["oauthClientSecret"] = state?.oauthClientSecret;
            resourceInputs["oauthTokenUrl"] = state?.oauthTokenUrl;
            resourceInputs["open"] = state?.open;
            resourceInputs["processed"] = state?.processed;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["signed"] = state?.signed;
            resourceInputs["spamReport"] = state?.spamReport;
            resourceInputs["unsubscribe"] = state?.unsubscribe;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as EventWebhookArgs | undefined;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["bounce"] = args?.bounce;
            resourceInputs["click"] = args?.click;
            resourceInputs["deferred"] = args?.deferred;
            resourceInputs["delivered"] = args?.delivered;
            resourceInputs["dropped"] = args?.dropped;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["groupResubscribe"] = args?.groupResubscribe;
            resourceInputs["groupUnsubscribe"] = args?.groupUnsubscribe;
            resourceInputs["oauthClientId"] = args?.oauthClientId;
            resourceInputs["oauthClientSecret"] = args?.oauthClientSecret ? pulumi.secret(args.oauthClientSecret) : undefined;
            resourceInputs["oauthTokenUrl"] = args?.oauthTokenUrl;
            resourceInputs["open"] = args?.open;
            resourceInputs["processed"] = args?.processed;
            resourceInputs["signed"] = args?.signed;
            resourceInputs["spamReport"] = args?.spamReport;
            resourceInputs["unsubscribe"] = args?.unsubscribe;
            resourceInputs["url"] = args?.url;
            resourceInputs["publicKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["oauthClientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(EventWebhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EventWebhook resources.
 */
export interface EventWebhookState {
    /**
     * Receiving server could not or would not accept message.
     */
    bounce?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient clicked on a link within the message. You need to enable Click Tracking for getting this type of event.
     */
    click?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient's email server temporarily rejected message.
     */
    deferred?: pulumi.Input<boolean | undefined>;
    /**
     * Message has been successfully delivered to the receiving server.
     */
    delivered?: pulumi.Input<boolean | undefined>;
    /**
     * You may see the following drop reasons: Invalid SMTPAPI header, Spam Content (if spam checker app enabled), Unsubscribed Address, Bounced Address, Spam Reporting Address, Invalid, Recipient List over Package Quota.
     */
    dropped?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates if the event webhook is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Friendly name for the webhook to help you identify it.
     */
    friendlyName?: pulumi.Input<string | undefined>;
    /**
     * Recipient resubscribes to specific group by updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    groupResubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient unsubscribe from specific group, by either direct link or updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    groupUnsubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * The client ID Twilio SendGrid sends to your OAuth server or service provider to generate an OAuth access token.
     */
    oauthClientId?: pulumi.Input<string | undefined>;
    /**
     * This secret is needed only once to create an access token. SendGrid will store this secret, allowing you to update your Client ID and Token URL without passing the secret to SendGrid again. When passing data in this field, you must also include the oauthClientId and oauthTokenUrl fields.
     */
    oauthClientSecret?: pulumi.Input<string | undefined>;
    /**
     * The URL where Twilio SendGrid sends the Client ID and Client Secret to generate an access token. This should be your OAuth server or service provider. When passing data in this field, you must also include the oauthClientId field.
     */
    oauthTokenUrl?: pulumi.Input<string | undefined>;
    /**
     * Recipient has opened the HTML message. You need to enable Open Tracking for getting this type of event.
     */
    open?: pulumi.Input<boolean | undefined>;
    /**
     * Message has been received and is ready to be delivered.
     */
    processed?: pulumi.Input<boolean | undefined>;
    /**
     * The public key used to sign the event webhook. Only present if 'signed' is true
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * Should the event webhook use signing?
     */
    signed?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient marked a message as spam.
     */
    spamReport?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient clicked on message's subscription management link. You need to enable Subscription Tracking for getting this type of event.
     */
    unsubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data events from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be eventd and POSTed to this URL.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EventWebhook resource.
 */
export interface EventWebhookArgs {
    /**
     * Receiving server could not or would not accept message.
     */
    bounce?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient clicked on a link within the message. You need to enable Click Tracking for getting this type of event.
     */
    click?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient's email server temporarily rejected message.
     */
    deferred?: pulumi.Input<boolean | undefined>;
    /**
     * Message has been successfully delivered to the receiving server.
     */
    delivered?: pulumi.Input<boolean | undefined>;
    /**
     * You may see the following drop reasons: Invalid SMTPAPI header, Spam Content (if spam checker app enabled), Unsubscribed Address, Bounced Address, Spam Reporting Address, Invalid, Recipient List over Package Quota.
     */
    dropped?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates if the event webhook is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Friendly name for the webhook to help you identify it.
     */
    friendlyName?: pulumi.Input<string | undefined>;
    /**
     * Recipient resubscribes to specific group by updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    groupResubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient unsubscribe from specific group, by either direct link or updating preferences. You need to enable Subscription Tracking for getting this type of event.
     */
    groupUnsubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * The client ID Twilio SendGrid sends to your OAuth server or service provider to generate an OAuth access token.
     */
    oauthClientId?: pulumi.Input<string | undefined>;
    /**
     * This secret is needed only once to create an access token. SendGrid will store this secret, allowing you to update your Client ID and Token URL without passing the secret to SendGrid again. When passing data in this field, you must also include the oauthClientId and oauthTokenUrl fields.
     */
    oauthClientSecret?: pulumi.Input<string | undefined>;
    /**
     * The URL where Twilio SendGrid sends the Client ID and Client Secret to generate an access token. This should be your OAuth server or service provider. When passing data in this field, you must also include the oauthClientId field.
     */
    oauthTokenUrl?: pulumi.Input<string | undefined>;
    /**
     * Recipient has opened the HTML message. You need to enable Open Tracking for getting this type of event.
     */
    open?: pulumi.Input<boolean | undefined>;
    /**
     * Message has been received and is ready to be delivered.
     */
    processed?: pulumi.Input<boolean | undefined>;
    /**
     * Should the event webhook use signing?
     */
    signed?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient marked a message as spam.
     */
    spamReport?: pulumi.Input<boolean | undefined>;
    /**
     * Recipient clicked on message's subscription management link. You need to enable Subscription Tracking for getting this type of event.
     */
    unsubscribe?: pulumi.Input<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data events from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be eventd and POSTed to this URL.
     */
    url: pulumi.Input<string>;
}
