// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTemplate(args?: GetTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sendgrid:index/getTemplate:getTemplate", {
        "generation": args.generation,
        "name": args.name,
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplate.
 */
export interface GetTemplateArgs {
    generation?: string;
    name?: string;
    templateId?: string;
}

/**
 * A collection of values returned by getTemplate.
 */
export interface GetTemplateResult {
    readonly generation: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly templateId?: string;
    readonly updatedAt: string;
}
export function getTemplateOutput(args?: GetTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sendgrid:index/getTemplate:getTemplate", {
        "generation": args.generation,
        "name": args.name,
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplate.
 */
export interface GetTemplateOutputArgs {
    generation?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    templateId?: pulumi.Input<string | undefined>;
}
