// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTemplateVersion(args: GetTemplateVersionArgs, opts?: pulumi.InvokeOptions): Promise<GetTemplateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sendgrid:index/getTemplateVersion:getTemplateVersion", {
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplateVersion.
 */
export interface GetTemplateVersionArgs {
    /**
     * ID of the transactional template.
     */
    templateId: string;
}

/**
 * A collection of values returned by getTemplateVersion.
 */
export interface GetTemplateVersionResult {
    /**
     * Set the version as the active version associated with the template. Only one version of a template can be active. The first version created for a template will automatically be set to Active. Allowed values: 0, 1.
     */
    readonly active: number;
    /**
     * The editor used in the UI, allowed values: code (default), design.
     */
    readonly editor: string;
    /**
     * If true (default), plain*content is always generated from html*content. If false, plainContent is not altered.
     */
    readonly generatePlainContent: boolean;
    /**
     * The HTML content of the version, maximum of 1048576 bytes allowed.
     */
    readonly htmlContent: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Name of the transactional template version, max length: 100.
     */
    readonly name: string;
    /**
     * Text/plain content of the transactional template version, maximum of 1048576 bytes allowed.
     */
    readonly plainContent: string;
    /**
     * Subject of the new transactional template version, max length: 255.
     */
    readonly subject: string;
    /**
     * ID of the transactional template.
     */
    readonly templateId: string;
    /**
     * For dynamic templates only, the mock json data that will be used for template preview and test sends.
     */
    readonly testData: string;
    /**
     * A thumbnail preview of the template's html content.
     */
    readonly thumbnailUrl: string;
    /**
     * The date and time that this transactional template version was updated.
     */
    readonly updatedAt: string;
}
export function getTemplateVersionOutput(args: GetTemplateVersionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTemplateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sendgrid:index/getTemplateVersion:getTemplateVersion", {
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplateVersion.
 */
export interface GetTemplateVersionOutputArgs {
    /**
     * ID of the transactional template.
     */
    templateId: pulumi.Input<string>;
}
