// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTemplateVersion(args: GetTemplateVersionArgs, opts?: pulumi.InvokeOptions): Promise<GetTemplateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sendgrid:index/getTemplateVersion:getTemplateVersion", {
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplateVersion.
 */
export interface GetTemplateVersionArgs {
    templateId: string;
}

/**
 * A collection of values returned by getTemplateVersion.
 */
export interface GetTemplateVersionResult {
    readonly active: number;
    readonly editor: string;
    readonly generatePlainContent: boolean;
    readonly htmlContent: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly plainContent: string;
    readonly subject: string;
    readonly templateId: string;
    readonly testData: string;
    readonly thumbnailUrl: string;
    readonly updatedAt: string;
}
export function getTemplateVersionOutput(args: GetTemplateVersionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTemplateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sendgrid:index/getTemplateVersion:getTemplateVersion", {
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTemplateVersion.
 */
export interface GetTemplateVersionOutputArgs {
    templateId: pulumi.Input<string>;
}
