// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getUnsubscribeGroup(args?: GetUnsubscribeGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetUnsubscribeGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sendgrid:index/getUnsubscribeGroup:getUnsubscribeGroup", {
        "groupId": args.groupId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getUnsubscribeGroup.
 */
export interface GetUnsubscribeGroupArgs {
    /**
     * The id of the unsubscribe group to retrieve
     */
    groupId?: string;
    /**
     * The name of the unsubscribe group to retrieve
     */
    name?: string;
}

/**
 * A collection of values returned by getUnsubscribeGroup.
 */
export interface GetUnsubscribeGroupResult {
    /**
     * The description of the unsubscribe group
     */
    readonly description: string;
    /**
     * The id of the unsubscribe group to retrieve
     */
    readonly groupId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Should this unsubscribe group be used as the default group?
     */
    readonly isDefault: boolean;
    /**
     * The name of the unsubscribe group to retrieve
     */
    readonly name?: string;
    /**
     * The number of unsubscribes that belong to the group.
     */
    readonly unsubscribes: number;
}
export function getUnsubscribeGroupOutput(args?: GetUnsubscribeGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUnsubscribeGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sendgrid:index/getUnsubscribeGroup:getUnsubscribeGroup", {
        "groupId": args.groupId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getUnsubscribeGroup.
 */
export interface GetUnsubscribeGroupOutputArgs {
    /**
     * The id of the unsubscribe group to retrieve
     */
    groupId?: pulumi.Input<string | undefined>;
    /**
     * The name of the unsubscribe group to retrieve
     */
    name?: pulumi.Input<string | undefined>;
}
