// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiKeyArgs, ApiKeyState } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { DomainAuthenticationArgs, DomainAuthenticationState } from "./domainAuthentication";
export type DomainAuthentication = import("./domainAuthentication").DomainAuthentication;
export const DomainAuthentication: typeof import("./domainAuthentication").DomainAuthentication = null as any;
utilities.lazyLoad(exports, ["DomainAuthentication"], () => require("./domainAuthentication"));

export { DomainAuthenticationValidationArgs, DomainAuthenticationValidationState } from "./domainAuthenticationValidation";
export type DomainAuthenticationValidation = import("./domainAuthenticationValidation").DomainAuthenticationValidation;
export const DomainAuthenticationValidation: typeof import("./domainAuthenticationValidation").DomainAuthenticationValidation = null as any;
utilities.lazyLoad(exports, ["DomainAuthenticationValidation"], () => require("./domainAuthenticationValidation"));

export { EventWebhookArgs, EventWebhookState } from "./eventWebhook";
export type EventWebhook = import("./eventWebhook").EventWebhook;
export const EventWebhook: typeof import("./eventWebhook").EventWebhook = null as any;
utilities.lazyLoad(exports, ["EventWebhook"], () => require("./eventWebhook"));

export { GetTeammateArgs, GetTeammateResult, GetTeammateOutputArgs } from "./getTeammate";
export const getTeammate: typeof import("./getTeammate").getTeammate = null as any;
export const getTeammateOutput: typeof import("./getTeammate").getTeammateOutput = null as any;
utilities.lazyLoad(exports, ["getTeammate","getTeammateOutput"], () => require("./getTeammate"));

export { GetTemplateArgs, GetTemplateResult, GetTemplateOutputArgs } from "./getTemplate";
export const getTemplate: typeof import("./getTemplate").getTemplate = null as any;
export const getTemplateOutput: typeof import("./getTemplate").getTemplateOutput = null as any;
utilities.lazyLoad(exports, ["getTemplate","getTemplateOutput"], () => require("./getTemplate"));

export { GetTemplateVersionArgs, GetTemplateVersionResult, GetTemplateVersionOutputArgs } from "./getTemplateVersion";
export const getTemplateVersion: typeof import("./getTemplateVersion").getTemplateVersion = null as any;
export const getTemplateVersionOutput: typeof import("./getTemplateVersion").getTemplateVersionOutput = null as any;
utilities.lazyLoad(exports, ["getTemplateVersion","getTemplateVersionOutput"], () => require("./getTemplateVersion"));

export { GetUnsubscribeGroupArgs, GetUnsubscribeGroupResult, GetUnsubscribeGroupOutputArgs } from "./getUnsubscribeGroup";
export const getUnsubscribeGroup: typeof import("./getUnsubscribeGroup").getUnsubscribeGroup = null as any;
export const getUnsubscribeGroupOutput: typeof import("./getUnsubscribeGroup").getUnsubscribeGroupOutput = null as any;
utilities.lazyLoad(exports, ["getUnsubscribeGroup","getUnsubscribeGroupOutput"], () => require("./getUnsubscribeGroup"));

export { LinkBrandingArgs, LinkBrandingState } from "./linkBranding";
export type LinkBranding = import("./linkBranding").LinkBranding;
export const LinkBranding: typeof import("./linkBranding").LinkBranding = null as any;
utilities.lazyLoad(exports, ["LinkBranding"], () => require("./linkBranding"));

export { ParseWebhookArgs, ParseWebhookState } from "./parseWebhook";
export type ParseWebhook = import("./parseWebhook").ParseWebhook;
export const ParseWebhook: typeof import("./parseWebhook").ParseWebhook = null as any;
utilities.lazyLoad(exports, ["ParseWebhook"], () => require("./parseWebhook"));

export * from "./provider";
import { Provider } from "./provider";

export { SsoCertificateArgs, SsoCertificateState } from "./ssoCertificate";
export type SsoCertificate = import("./ssoCertificate").SsoCertificate;
export const SsoCertificate: typeof import("./ssoCertificate").SsoCertificate = null as any;
utilities.lazyLoad(exports, ["SsoCertificate"], () => require("./ssoCertificate"));

export { SsoIntegrationArgs, SsoIntegrationState } from "./ssoIntegration";
export type SsoIntegration = import("./ssoIntegration").SsoIntegration;
export const SsoIntegration: typeof import("./ssoIntegration").SsoIntegration = null as any;
utilities.lazyLoad(exports, ["SsoIntegration"], () => require("./ssoIntegration"));

export { SubuserArgs, SubuserState } from "./subuser";
export type Subuser = import("./subuser").Subuser;
export const Subuser: typeof import("./subuser").Subuser = null as any;
utilities.lazyLoad(exports, ["Subuser"], () => require("./subuser"));

export { TeammateArgs, TeammateState } from "./teammate";
export type Teammate = import("./teammate").Teammate;
export const Teammate: typeof import("./teammate").Teammate = null as any;
utilities.lazyLoad(exports, ["Teammate"], () => require("./teammate"));

export { TemplateArgs, TemplateState } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));

export { TemplateVersionArgs, TemplateVersionState } from "./templateVersion";
export type TemplateVersion = import("./templateVersion").TemplateVersion;
export const TemplateVersion: typeof import("./templateVersion").TemplateVersion = null as any;
utilities.lazyLoad(exports, ["TemplateVersion"], () => require("./templateVersion"));

export { UnsubscribeGroupArgs, UnsubscribeGroupState } from "./unsubscribeGroup";
export type UnsubscribeGroup = import("./unsubscribeGroup").UnsubscribeGroup;
export const UnsubscribeGroup: typeof import("./unsubscribeGroup").UnsubscribeGroup = null as any;
utilities.lazyLoad(exports, ["UnsubscribeGroup"], () => require("./unsubscribeGroup"));

export { WebhookSecurityPolicyArgs, WebhookSecurityPolicyState } from "./webhookSecurityPolicy";
export type WebhookSecurityPolicy = import("./webhookSecurityPolicy").WebhookSecurityPolicy;
export const WebhookSecurityPolicy: typeof import("./webhookSecurityPolicy").WebhookSecurityPolicy = null as any;
utilities.lazyLoad(exports, ["WebhookSecurityPolicy"], () => require("./webhookSecurityPolicy"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sendgrid:index/apiKey:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "sendgrid:index/domainAuthentication:DomainAuthentication":
                return new DomainAuthentication(name, <any>undefined, { urn })
            case "sendgrid:index/domainAuthenticationValidation:DomainAuthenticationValidation":
                return new DomainAuthenticationValidation(name, <any>undefined, { urn })
            case "sendgrid:index/eventWebhook:EventWebhook":
                return new EventWebhook(name, <any>undefined, { urn })
            case "sendgrid:index/linkBranding:LinkBranding":
                return new LinkBranding(name, <any>undefined, { urn })
            case "sendgrid:index/parseWebhook:ParseWebhook":
                return new ParseWebhook(name, <any>undefined, { urn })
            case "sendgrid:index/ssoCertificate:SsoCertificate":
                return new SsoCertificate(name, <any>undefined, { urn })
            case "sendgrid:index/ssoIntegration:SsoIntegration":
                return new SsoIntegration(name, <any>undefined, { urn })
            case "sendgrid:index/subuser:Subuser":
                return new Subuser(name, <any>undefined, { urn })
            case "sendgrid:index/teammate:Teammate":
                return new Teammate(name, <any>undefined, { urn })
            case "sendgrid:index/template:Template":
                return new Template(name, <any>undefined, { urn })
            case "sendgrid:index/templateVersion:TemplateVersion":
                return new TemplateVersion(name, <any>undefined, { urn })
            case "sendgrid:index/unsubscribeGroup:UnsubscribeGroup":
                return new UnsubscribeGroup(name, <any>undefined, { urn })
            case "sendgrid:index/webhookSecurityPolicy:WebhookSecurityPolicy":
                return new WebhookSecurityPolicy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sendgrid", "index/apiKey", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/domainAuthentication", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/domainAuthenticationValidation", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/eventWebhook", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/linkBranding", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/parseWebhook", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/ssoCertificate", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/ssoIntegration", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/subuser", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/teammate", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/template", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/templateVersion", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/unsubscribeGroup", _module)
pulumi.runtime.registerResourceModule("sendgrid", "index/webhookSecurityPolicy", _module)
pulumi.runtime.registerResourcePackage("sendgrid", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:sendgrid") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
