// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ParseWebhook extends pulumi.CustomResource {
    /**
     * Get an existing ParseWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ParseWebhookState, opts?: pulumi.CustomResourceOptions): ParseWebhook {
        return new ParseWebhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/parseWebhook:ParseWebhook';

    /**
     * Returns true if the given object is an instance of ParseWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ParseWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ParseWebhook.__pulumiType;
    }

    /**
     * A specific and unique domain or subdomain that you have created to use exclusively to parse your incoming email. For example, parse.yourdomain.com.
     */
    declare public readonly hostname: pulumi.Output<string>;
    /**
     * Indicates if you would like SendGrid to post the original MIME-type content of your parsed email. When this parameter is set to "true", SendGrid will send a JSON payload of the content of your email.
     */
    declare public readonly sendRaw: pulumi.Output<boolean | undefined>;
    /**
     * Indicates if you would like SendGrid to check the content parsed from your emails for spam before POSTing them to your domain.
     */
    declare public readonly spamCheck: pulumi.Output<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data parsed from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be parsed and POSTed to this URL.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * The ID of the webhook security policy to apply to this parse webhook. See the `sendgrid.WebhookSecurityPolicy` resource for more details.
     */
    declare public readonly webhookSecurityPolicyId: pulumi.Output<string | undefined>;

    /**
     * Create a ParseWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ParseWebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ParseWebhookArgs | ParseWebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ParseWebhookState | undefined;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["sendRaw"] = state?.sendRaw;
            resourceInputs["spamCheck"] = state?.spamCheck;
            resourceInputs["url"] = state?.url;
            resourceInputs["webhookSecurityPolicyId"] = state?.webhookSecurityPolicyId;
        } else {
            const args = argsOrState as ParseWebhookArgs | undefined;
            if (args?.hostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["sendRaw"] = args?.sendRaw;
            resourceInputs["spamCheck"] = args?.spamCheck;
            resourceInputs["url"] = args?.url;
            resourceInputs["webhookSecurityPolicyId"] = args?.webhookSecurityPolicyId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ParseWebhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ParseWebhook resources.
 */
export interface ParseWebhookState {
    /**
     * A specific and unique domain or subdomain that you have created to use exclusively to parse your incoming email. For example, parse.yourdomain.com.
     */
    hostname?: pulumi.Input<string | undefined>;
    /**
     * Indicates if you would like SendGrid to post the original MIME-type content of your parsed email. When this parameter is set to "true", SendGrid will send a JSON payload of the content of your email.
     */
    sendRaw?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates if you would like SendGrid to check the content parsed from your emails for spam before POSTing them to your domain.
     */
    spamCheck?: pulumi.Input<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data parsed from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be parsed and POSTed to this URL.
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * The ID of the webhook security policy to apply to this parse webhook. See the `sendgrid.WebhookSecurityPolicy` resource for more details.
     */
    webhookSecurityPolicyId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ParseWebhook resource.
 */
export interface ParseWebhookArgs {
    /**
     * A specific and unique domain or subdomain that you have created to use exclusively to parse your incoming email. For example, parse.yourdomain.com.
     */
    hostname: pulumi.Input<string>;
    /**
     * Indicates if you would like SendGrid to post the original MIME-type content of your parsed email. When this parameter is set to "true", SendGrid will send a JSON payload of the content of your email.
     */
    sendRaw?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates if you would like SendGrid to check the content parsed from your emails for spam before POSTing them to your domain.
     */
    spamCheck?: pulumi.Input<boolean | undefined>;
    /**
     * The public URL where you would like SendGrid to POST the data parsed from your email. Any emails sent with the given hostname provided (whose MX records have been updated to point to SendGrid) will be parsed and POSTed to this URL.
     */
    url: pulumi.Input<string>;
    /**
     * The ID of the webhook security policy to apply to this parse webhook. See the `sendgrid.WebhookSecurityPolicy` resource for more details.
     */
    webhookSecurityPolicyId?: pulumi.Input<string | undefined>;
}
