// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SsoCertificate extends pulumi.CustomResource {
    /**
     * Get an existing SsoCertificate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SsoCertificateState, opts?: pulumi.CustomResourceOptions): SsoCertificate {
        return new SsoCertificate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/ssoCertificate:SsoCertificate';

    /**
     * Returns true if the given object is an instance of SsoCertificate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SsoCertificate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SsoCertificate.__pulumiType;
    }

    /**
     * An ID that matches an existing SSO integration.
     */
    declare public readonly integrationId: pulumi.Output<string>;
    /**
     * This public certificate allows SendGrid to verify that
     * 					SAML requests it receives are signed by an IdP that it recognizes.
     */
    declare public readonly publicCertificate: pulumi.Output<string>;

    /**
     * Create a SsoCertificate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SsoCertificateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SsoCertificateArgs | SsoCertificateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SsoCertificateState | undefined;
            resourceInputs["integrationId"] = state?.integrationId;
            resourceInputs["publicCertificate"] = state?.publicCertificate;
        } else {
            const args = argsOrState as SsoCertificateArgs | undefined;
            if (args?.integrationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'integrationId'");
            }
            if (args?.publicCertificate === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicCertificate'");
            }
            resourceInputs["integrationId"] = args?.integrationId;
            resourceInputs["publicCertificate"] = args?.publicCertificate;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SsoCertificate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SsoCertificate resources.
 */
export interface SsoCertificateState {
    /**
     * An ID that matches an existing SSO integration.
     */
    integrationId?: pulumi.Input<string | undefined>;
    /**
     * This public certificate allows SendGrid to verify that
     * 					SAML requests it receives are signed by an IdP that it recognizes.
     */
    publicCertificate?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SsoCertificate resource.
 */
export interface SsoCertificateArgs {
    /**
     * An ID that matches an existing SSO integration.
     */
    integrationId: pulumi.Input<string>;
    /**
     * This public certificate allows SendGrid to verify that
     * 					SAML requests it receives are signed by an IdP that it recognizes.
     */
    publicCertificate: pulumi.Input<string>;
}
