// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SsoIntegration extends pulumi.CustomResource {
    /**
     * Get an existing SsoIntegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SsoIntegrationState, opts?: pulumi.CustomResourceOptions): SsoIntegration {
        return new SsoIntegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/ssoIntegration:SsoIntegration';

    /**
     * Returns true if the given object is an instance of SsoIntegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SsoIntegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SsoIntegration.__pulumiType;
    }

    /**
     * The URL where your IdP should POST its SAML response.
     * 					This is the Twilio SendGrid URL that is responsible for receiving and parsing a SAML assertion.
     * 					This is the same URL as the Single Sign-On URL when using SendGrid.
     */
    declare public /*out*/ readonly audienceUrl: pulumi.Output<string>;
    /**
     * Indicates if the integration is complete.
     */
    declare public /*out*/ readonly completedIntegration: pulumi.Output<boolean>;
    /**
     * Indicates if the integration is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * An identifier provided by your IdP to identify Twilio SendGrid in the SAML interaction.
     * 					This is called the 'SAML Issuer ID' in the Twilio SendGrid UI.
     */
    declare public readonly entityId: pulumi.Output<string | undefined>;
    /**
     * The name of the integration.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The IdP's SAML POST endpoint. This endpoint should receive requests
     * 					and initiate an SSO login flow. This is called the 'Embed Link' in the Twilio SendGrid UI.
     */
    declare public readonly signinUrl: pulumi.Output<string | undefined>;
    /**
     * This URL is relevant only for an IdP-initiated authentication flow.
     * 					If a user authenticates from their IdP, this URL will return them to their IdP when logging out.
     */
    declare public readonly signoutUrl: pulumi.Output<string | undefined>;
    /**
     * The URL where your IdP should POST its SAML response.
     * 					This is the Twilio SendGrid URL that is responsible for receiving and parsing a SAML assertion.
     * 					This is the same URL as the Audience URL when using SendGrid.
     */
    declare public /*out*/ readonly singleSignonUrl: pulumi.Output<string>;

    /**
     * Create a SsoIntegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SsoIntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SsoIntegrationArgs | SsoIntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SsoIntegrationState | undefined;
            resourceInputs["audienceUrl"] = state?.audienceUrl;
            resourceInputs["completedIntegration"] = state?.completedIntegration;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["entityId"] = state?.entityId;
            resourceInputs["name"] = state?.name;
            resourceInputs["signinUrl"] = state?.signinUrl;
            resourceInputs["signoutUrl"] = state?.signoutUrl;
            resourceInputs["singleSignonUrl"] = state?.singleSignonUrl;
        } else {
            const args = argsOrState as SsoIntegrationArgs | undefined;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["entityId"] = args?.entityId;
            resourceInputs["name"] = args?.name;
            resourceInputs["signinUrl"] = args?.signinUrl;
            resourceInputs["signoutUrl"] = args?.signoutUrl;
            resourceInputs["audienceUrl"] = undefined /*out*/;
            resourceInputs["completedIntegration"] = undefined /*out*/;
            resourceInputs["singleSignonUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SsoIntegration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SsoIntegration resources.
 */
export interface SsoIntegrationState {
    /**
     * The URL where your IdP should POST its SAML response.
     * 					This is the Twilio SendGrid URL that is responsible for receiving and parsing a SAML assertion.
     * 					This is the same URL as the Single Sign-On URL when using SendGrid.
     */
    audienceUrl?: pulumi.Input<string | undefined>;
    /**
     * Indicates if the integration is complete.
     */
    completedIntegration?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates if the integration is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * An identifier provided by your IdP to identify Twilio SendGrid in the SAML interaction.
     * 					This is called the 'SAML Issuer ID' in the Twilio SendGrid UI.
     */
    entityId?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The IdP's SAML POST endpoint. This endpoint should receive requests
     * 					and initiate an SSO login flow. This is called the 'Embed Link' in the Twilio SendGrid UI.
     */
    signinUrl?: pulumi.Input<string | undefined>;
    /**
     * This URL is relevant only for an IdP-initiated authentication flow.
     * 					If a user authenticates from their IdP, this URL will return them to their IdP when logging out.
     */
    signoutUrl?: pulumi.Input<string | undefined>;
    /**
     * The URL where your IdP should POST its SAML response.
     * 					This is the Twilio SendGrid URL that is responsible for receiving and parsing a SAML assertion.
     * 					This is the same URL as the Audience URL when using SendGrid.
     */
    singleSignonUrl?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SsoIntegration resource.
 */
export interface SsoIntegrationArgs {
    /**
     * Indicates if the integration is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * An identifier provided by your IdP to identify Twilio SendGrid in the SAML interaction.
     * 					This is called the 'SAML Issuer ID' in the Twilio SendGrid UI.
     */
    entityId?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The IdP's SAML POST endpoint. This endpoint should receive requests
     * 					and initiate an SSO login flow. This is called the 'Embed Link' in the Twilio SendGrid UI.
     */
    signinUrl?: pulumi.Input<string | undefined>;
    /**
     * This URL is relevant only for an IdP-initiated authentication flow.
     * 					If a user authenticates from their IdP, this URL will return them to their IdP when logging out.
     */
    signoutUrl?: pulumi.Input<string | undefined>;
}
