// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Subuser extends pulumi.CustomResource {
    /**
     * Get an existing Subuser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SubuserState, opts?: pulumi.CustomResourceOptions): Subuser {
        return new Subuser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/subuser:Subuser';

    /**
     * Returns true if the given object is an instance of Subuser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Subuser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Subuser.__pulumiType;
    }

    declare public /*out*/ readonly authorizationToken: pulumi.Output<string>;
    declare public /*out*/ readonly creditAllocationType: pulumi.Output<string>;
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * The email of the subuser.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The IP addresses that should be assigned to this subuser.
     */
    declare public readonly ips: pulumi.Output<string[]>;
    /**
     * The password the subuser will use when logging into SendGrid.
     */
    declare public readonly password: pulumi.Output<string>;
    declare public /*out*/ readonly signupSessionToken: pulumi.Output<string>;
    declare public /*out*/ readonly userId: pulumi.Output<number>;
    /**
     * The name of the subuser.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a Subuser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SubuserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubuserArgs | SubuserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SubuserState | undefined;
            resourceInputs["authorizationToken"] = state?.authorizationToken;
            resourceInputs["creditAllocationType"] = state?.creditAllocationType;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["email"] = state?.email;
            resourceInputs["ips"] = state?.ips;
            resourceInputs["password"] = state?.password;
            resourceInputs["signupSessionToken"] = state?.signupSessionToken;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as SubuserArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.ips === undefined && !opts.urn) {
                throw new Error("Missing required property 'ips'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["email"] = args?.email;
            resourceInputs["ips"] = args?.ips;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["username"] = args?.username;
            resourceInputs["authorizationToken"] = undefined /*out*/;
            resourceInputs["creditAllocationType"] = undefined /*out*/;
            resourceInputs["signupSessionToken"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Subuser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Subuser resources.
 */
export interface SubuserState {
    authorizationToken?: pulumi.Input<string | undefined>;
    creditAllocationType?: pulumi.Input<string | undefined>;
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The email of the subuser.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The IP addresses that should be assigned to this subuser.
     */
    ips?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The password the subuser will use when logging into SendGrid.
     */
    password?: pulumi.Input<string | undefined>;
    signupSessionToken?: pulumi.Input<string | undefined>;
    userId?: pulumi.Input<number | undefined>;
    /**
     * The name of the subuser.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Subuser resource.
 */
export interface SubuserArgs {
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The email of the subuser.
     */
    email: pulumi.Input<string>;
    /**
     * The IP addresses that should be assigned to this subuser.
     */
    ips: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The password the subuser will use when logging into SendGrid.
     */
    password: pulumi.Input<string>;
    /**
     * The name of the subuser.
     */
    username: pulumi.Input<string>;
}
