// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid teammate. Teammates are team members who have access to your SendGrid account with specific permissions.
 *
 * **Important Notes:**
 * - Admin teammates have full access and don't need scopes
 * - Scopes '2fa_exempt' and '2fa_required' are set automatically by SendGrid
 * - Self-service credential scopes (user.password.*, user.multifactor_authentication.*, user.email.update, user.username.update) are granted automatically by SendGrid to password-login teammates and cannot be assigned manually
 * - 'user.profile.update' is accepted on write and then omitted from the next read, so Terraform can never converge on it: it is rejected in configuration, stripped from writes, and filtered out of state
 * - Some scopes require specific SendGrid plans (Pro+, Marketing plans, etc.)
 * - Use timeouts for better reliability with rate limiting
 *
 * ## Example Usage
 *
 * ### Basic Teammate
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * const example = new sendgrid.Teammate("example", {
 *     email: "teammate@example.com",
 *     isAdmin: false,
 *     isSso: false,
 *     scopes: [
 *         "mail.send",
 *         "templates.read",
 *     ],
 * });
 * ```
 *
 * ### Admin Teammate
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * // Admin teammate - no scopes needed
 * const admin = new sendgrid.Teammate("admin", {
 *     email: "admin@example.com",
 *     isAdmin: true,
 *     isSso: false,
 * });
 * ```
 *
 * ### SSO User
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * // SSO teammate with first and last name
 * const ssoUser = new sendgrid.Teammate("sso_user", {
 *     email: "sso.user@example.com",
 *     firstName: "John",
 *     lastName: "Doe",
 *     isAdmin: false,
 *     isSso: true,
 *     scopes: [
 *         "mail.send",
 *         "stats.read",
 *     ],
 * });
 * ```
 *
 * ### Marketing Team Member
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * // Marketing teammate with extended permissions
 * const marketing = new sendgrid.Teammate("marketing", {
 *     email: "marketing@example.com",
 *     isAdmin: false,
 *     isSso: false,
 *     scopes: [
 *         "mail.send",
 *         "marketing.read",
 *         "marketing.automation.read",
 *         "templates.read",
 *         "templates.create",
 *         "templates.update",
 *         "stats.read",
 *     ],
 * });
 * ```
 *
 * ### Bulk Creation
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * const developers = {
 *     dev1: {
 *         email: "dev1@example.com",
 *         scopes: [
 *             "mail.send",
 *             "templates.read",
 *         ],
 *     },
 *     dev2: {
 *         email: "dev2@example.com",
 *         scopes: [
 *             "mail.send",
 *             "templates.read",
 *             "stats.read",
 *         ],
 *     },
 *     dev3: {
 *         email: "dev3@example.com",
 *         scopes: ["mail.send"],
 *     },
 * };
 * const developersTeammate: sendgrid.Teammate[] = [];
 * for (const range of Object.entries(developers).sort().map(([k, v]) => ({key: k, value: v}))) {
 *     developersTeammate.push(new sendgrid.Teammate(`developers-${range.key}`, {
 *         email: range.value.email,
 *         isAdmin: false,
 *         isSso: false,
 *         scopes: range.value.scopes,
 *     }));
 * }
 * ```
 *
 * ## Import
 *
 * Import existing teammate by email
 *
 * ```sh
 * $ pulumi import sendgrid:index/teammate:Teammate example teammate@example.com
 * ```
 */
export class Teammate extends pulumi.CustomResource {
    /**
     * Get an existing Teammate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeammateState, opts?: pulumi.CustomResourceOptions): Teammate {
        return new Teammate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/teammate:Teammate';

    /**
     * Returns true if the given object is an instance of Teammate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Teammate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Teammate.__pulumiType;
    }

    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    declare public readonly firstName: pulumi.Output<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    declare public readonly isAdmin: pulumi.Output<boolean>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require first*name and last*name.
     */
    declare public readonly isSso: pulumi.Output<boolean>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    declare public readonly lastName: pulumi.Output<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if is*admin is true. Cannot include '2fa*exempt' or '2fa*required' as these are managed automatically by SendGrid. This attribute is also computed: leaving it unset keeps whatever scopes the teammate currently has on the server instead of clearing them, and it must be left unset for a teammate with subuser*access, because SendGrid refuses root scopes for those teammates. See SendGrid API documentation for available scopes.
     */
    declare public readonly scopes: pulumi.Output<string[]>;
    /**
     * Subuser permission grants for this SSO teammate. Only applies when `isSso = true`. Setting at least one block sets `hasRestrictedSubuserAccess = true` on the API. This attribute is also computed: when no block is managed it reflects the teammate's current server-side access without producing a diff, and removing all blocks falls back to that server value rather than clearing access (Terraform does not clobber access it does not manage).
     */
    declare public readonly subuserAccesses: pulumi.Output<outputs.TeammateSubuserAccess[]>;
    /**
     * The status of the user: 'active' for confirmed users, 'pending' for users who haven't accepted their invitation yet.
     */
    declare public /*out*/ readonly userStatus: pulumi.Output<string>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Teammate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeammateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeammateArgs | TeammateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeammateState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["firstName"] = state?.firstName;
            resourceInputs["isAdmin"] = state?.isAdmin;
            resourceInputs["isSso"] = state?.isSso;
            resourceInputs["lastName"] = state?.lastName;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["subuserAccesses"] = state?.subuserAccesses;
            resourceInputs["userStatus"] = state?.userStatus;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as TeammateArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.isAdmin === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAdmin'");
            }
            if (args?.isSso === undefined && !opts.urn) {
                throw new Error("Missing required property 'isSso'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["firstName"] = args?.firstName;
            resourceInputs["isAdmin"] = args?.isAdmin;
            resourceInputs["isSso"] = args?.isSso;
            resourceInputs["lastName"] = args?.lastName;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["subuserAccesses"] = args?.subuserAccesses;
            resourceInputs["username"] = args?.username;
            resourceInputs["userStatus"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Teammate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Teammate resources.
 */
export interface TeammateState {
    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    isAdmin?: pulumi.Input<boolean | undefined>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require first*name and last*name.
     */
    isSso?: pulumi.Input<boolean | undefined>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if is*admin is true. Cannot include '2fa*exempt' or '2fa*required' as these are managed automatically by SendGrid. This attribute is also computed: leaving it unset keeps whatever scopes the teammate currently has on the server instead of clearing them, and it must be left unset for a teammate with subuser*access, because SendGrid refuses root scopes for those teammates. See SendGrid API documentation for available scopes.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Subuser permission grants for this SSO teammate. Only applies when `isSso = true`. Setting at least one block sets `hasRestrictedSubuserAccess = true` on the API. This attribute is also computed: when no block is managed it reflects the teammate's current server-side access without producing a diff, and removing all blocks falls back to that server value rather than clearing access (Terraform does not clobber access it does not manage).
     */
    subuserAccesses?: pulumi.Input<pulumi.Input<inputs.TeammateSubuserAccess>[] | undefined>;
    /**
     * The status of the user: 'active' for confirmed users, 'pending' for users who haven't accepted their invitation yet.
     */
    userStatus?: pulumi.Input<string | undefined>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Teammate resource.
 */
export interface TeammateArgs {
    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    email: pulumi.Input<string>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    isAdmin: pulumi.Input<boolean>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require first*name and last*name.
     */
    isSso: pulumi.Input<boolean>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if is*admin is true. Cannot include '2fa*exempt' or '2fa*required' as these are managed automatically by SendGrid. This attribute is also computed: leaving it unset keeps whatever scopes the teammate currently has on the server instead of clearing them, and it must be left unset for a teammate with subuser*access, because SendGrid refuses root scopes for those teammates. See SendGrid API documentation for available scopes.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Subuser permission grants for this SSO teammate. Only applies when `isSso = true`. Setting at least one block sets `hasRestrictedSubuserAccess = true` on the API. This attribute is also computed: when no block is managed it reflects the teammate's current server-side access without producing a diff, and removing all blocks falls back to that server value rather than clearing access (Terraform does not clobber access it does not manage).
     */
    subuserAccesses?: pulumi.Input<pulumi.Input<inputs.TeammateSubuserAccess>[] | undefined>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    username?: pulumi.Input<string | undefined>;
}
