// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Teammate extends pulumi.CustomResource {
    /**
     * Get an existing Teammate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeammateState, opts?: pulumi.CustomResourceOptions): Teammate {
        return new Teammate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/teammate:Teammate';

    /**
     * Returns true if the given object is an instance of Teammate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Teammate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Teammate.__pulumiType;
    }

    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    declare public readonly firstName: pulumi.Output<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    declare public readonly isAdmin: pulumi.Output<boolean>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require firstName and last_name.
     */
    declare public readonly isSso: pulumi.Output<boolean>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    declare public readonly lastName: pulumi.Output<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if isAdmin is true. Cannot include '2fa_exempt' or '2fa_required' as these are managed automatically by SendGrid. See SendGrid API documentation for available scopes.
     */
    declare public readonly scopes: pulumi.Output<string[] | undefined>;
    /**
     * The status of the user: 'active' for confirmed users, 'pending' for users who haven't accepted their invitation yet.
     */
    declare public /*out*/ readonly userStatus: pulumi.Output<string>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Teammate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeammateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeammateArgs | TeammateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeammateState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["firstName"] = state?.firstName;
            resourceInputs["isAdmin"] = state?.isAdmin;
            resourceInputs["isSso"] = state?.isSso;
            resourceInputs["lastName"] = state?.lastName;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["userStatus"] = state?.userStatus;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as TeammateArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.isAdmin === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAdmin'");
            }
            if (args?.isSso === undefined && !opts.urn) {
                throw new Error("Missing required property 'isSso'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["firstName"] = args?.firstName;
            resourceInputs["isAdmin"] = args?.isAdmin;
            resourceInputs["isSso"] = args?.isSso;
            resourceInputs["lastName"] = args?.lastName;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["username"] = args?.username;
            resourceInputs["userStatus"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Teammate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Teammate resources.
 */
export interface TeammateState {
    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    isAdmin?: pulumi.Input<boolean | undefined>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require firstName and last_name.
     */
    isSso?: pulumi.Input<boolean | undefined>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if isAdmin is true. Cannot include '2fa_exempt' or '2fa_required' as these are managed automatically by SendGrid. See SendGrid API documentation for available scopes.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The status of the user: 'active' for confirmed users, 'pending' for users who haven't accepted their invitation yet.
     */
    userStatus?: pulumi.Input<string | undefined>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Teammate resource.
 */
export interface TeammateArgs {
    /**
     * The email address of the teammate. This will be used as the teammate's login.
     */
    email: pulumi.Input<string>;
    /**
     * The first name of the teammate. Required for SSO users.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * Whether the teammate should have admin privileges. Admin teammates have full access to the account and don't need specific scopes.
     */
    isAdmin: pulumi.Input<boolean>;
    /**
     * Whether this is a Single Sign-On (SSO) user. SSO users require firstName and last_name.
     */
    isSso: pulumi.Input<boolean>;
    /**
     * The last name of the teammate. Required for SSO users.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * List of permission scopes for the teammate. Ignored if isAdmin is true. Cannot include '2fa_exempt' or '2fa_required' as these are managed automatically by SendGrid. See SendGrid API documentation for available scopes.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The username for the teammate. If not provided, the email will be used.
     */
    username?: pulumi.Input<string | undefined>;
}
