// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TemplateVersion extends pulumi.CustomResource {
    /**
     * Get an existing TemplateVersion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TemplateVersionState, opts?: pulumi.CustomResourceOptions): TemplateVersion {
        return new TemplateVersion(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/templateVersion:TemplateVersion';

    /**
     * Returns true if the given object is an instance of TemplateVersion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TemplateVersion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TemplateVersion.__pulumiType;
    }

    /**
     * Set the version as the active version associated with the template. Only one version of a template can be active. The first version created for a template will automatically be set to Active. Allowed values: 0, 1.
     */
    declare public readonly active: pulumi.Output<number | undefined>;
    /**
     * The editor used in the UI, allowed values: code (default), design.
     */
    declare public readonly editor: pulumi.Output<string | undefined>;
    /**
     * If true (default), plainContent is always generated from html_content. If false, plainContent is not altered.
     */
    declare public readonly generatePlainContent: pulumi.Output<boolean | undefined>;
    /**
     * The HTML content of the version, maximum of 1048576 bytes allowed.
     */
    declare public readonly htmlContent: pulumi.Output<string | undefined>;
    /**
     * Name of the transactional template version, max length: 100.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Text/plain content of the transactional template version, maximum of 1048576 bytes allowed.
     */
    declare public readonly plainContent: pulumi.Output<string>;
    /**
     * Subject of the new transactional template version, max length: 255.
     */
    declare public readonly subject: pulumi.Output<string>;
    /**
     * ID of the transactional template.
     */
    declare public readonly templateId: pulumi.Output<string>;
    /**
     * For dynamic templates only, the mock json data that will be used for template preview and test sends.
     */
    declare public readonly testData: pulumi.Output<string | undefined>;
    /**
     * A thumbnail preview of the template's html content.
     */
    declare public /*out*/ readonly thumbnailUrl: pulumi.Output<string>;
    /**
     * The date and time that this transactional template version was updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a TemplateVersion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TemplateVersionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TemplateVersionArgs | TemplateVersionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TemplateVersionState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["editor"] = state?.editor;
            resourceInputs["generatePlainContent"] = state?.generatePlainContent;
            resourceInputs["htmlContent"] = state?.htmlContent;
            resourceInputs["name"] = state?.name;
            resourceInputs["plainContent"] = state?.plainContent;
            resourceInputs["subject"] = state?.subject;
            resourceInputs["templateId"] = state?.templateId;
            resourceInputs["testData"] = state?.testData;
            resourceInputs["thumbnailUrl"] = state?.thumbnailUrl;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as TemplateVersionArgs | undefined;
            if (args?.subject === undefined && !opts.urn) {
                throw new Error("Missing required property 'subject'");
            }
            if (args?.templateId === undefined && !opts.urn) {
                throw new Error("Missing required property 'templateId'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["editor"] = args?.editor;
            resourceInputs["generatePlainContent"] = args?.generatePlainContent;
            resourceInputs["htmlContent"] = args?.htmlContent;
            resourceInputs["name"] = args?.name;
            resourceInputs["plainContent"] = args?.plainContent;
            resourceInputs["subject"] = args?.subject;
            resourceInputs["templateId"] = args?.templateId;
            resourceInputs["testData"] = args?.testData;
            resourceInputs["thumbnailUrl"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TemplateVersion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TemplateVersion resources.
 */
export interface TemplateVersionState {
    /**
     * Set the version as the active version associated with the template. Only one version of a template can be active. The first version created for a template will automatically be set to Active. Allowed values: 0, 1.
     */
    active?: pulumi.Input<number | undefined>;
    /**
     * The editor used in the UI, allowed values: code (default), design.
     */
    editor?: pulumi.Input<string | undefined>;
    /**
     * If true (default), plainContent is always generated from html_content. If false, plainContent is not altered.
     */
    generatePlainContent?: pulumi.Input<boolean | undefined>;
    /**
     * The HTML content of the version, maximum of 1048576 bytes allowed.
     */
    htmlContent?: pulumi.Input<string | undefined>;
    /**
     * Name of the transactional template version, max length: 100.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Text/plain content of the transactional template version, maximum of 1048576 bytes allowed.
     */
    plainContent?: pulumi.Input<string | undefined>;
    /**
     * Subject of the new transactional template version, max length: 255.
     */
    subject?: pulumi.Input<string | undefined>;
    /**
     * ID of the transactional template.
     */
    templateId?: pulumi.Input<string | undefined>;
    /**
     * For dynamic templates only, the mock json data that will be used for template preview and test sends.
     */
    testData?: pulumi.Input<string | undefined>;
    /**
     * A thumbnail preview of the template's html content.
     */
    thumbnailUrl?: pulumi.Input<string | undefined>;
    /**
     * The date and time that this transactional template version was updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TemplateVersion resource.
 */
export interface TemplateVersionArgs {
    /**
     * Set the version as the active version associated with the template. Only one version of a template can be active. The first version created for a template will automatically be set to Active. Allowed values: 0, 1.
     */
    active?: pulumi.Input<number | undefined>;
    /**
     * The editor used in the UI, allowed values: code (default), design.
     */
    editor?: pulumi.Input<string | undefined>;
    /**
     * If true (default), plainContent is always generated from html_content. If false, plainContent is not altered.
     */
    generatePlainContent?: pulumi.Input<boolean | undefined>;
    /**
     * The HTML content of the version, maximum of 1048576 bytes allowed.
     */
    htmlContent?: pulumi.Input<string | undefined>;
    /**
     * Name of the transactional template version, max length: 100.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Text/plain content of the transactional template version, maximum of 1048576 bytes allowed.
     */
    plainContent?: pulumi.Input<string | undefined>;
    /**
     * Subject of the new transactional template version, max length: 255.
     */
    subject: pulumi.Input<string>;
    /**
     * ID of the transactional template.
     */
    templateId: pulumi.Input<string>;
    /**
     * For dynamic templates only, the mock json data that will be used for template preview and test sends.
     */
    testData?: pulumi.Input<string | undefined>;
}
