// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sendgrid from "@nellisauction/pulumi-sendgrid";
 *
 * // Default unsubscribe group for general emails
 * const general = new sendgrid.UnsubscribeGroup("general", {
 *     name: "General Communications",
 *     description: "General company communications and updates",
 *     isDefault: true,
 * });
 * // Marketing emails unsubscribe group
 * const marketing = new sendgrid.UnsubscribeGroup("marketing", {
 *     name: "Marketing Emails",
 *     description: "Promotional offers, newsletters, and marketing content",
 *     isDefault: false,
 * });
 * // Transactional emails unsubscribe group
 * const transactional = new sendgrid.UnsubscribeGroup("transactional", {
 *     name: "Account Notifications",
 *     description: "Account-related notifications and alerts",
 *     isDefault: false,
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * !/bin/bash
 *
 * Import an existing unsubscribe group using its ID
 * Replace '12345' with your actual unsubscribe group ID
 *
 * ```sh
 * $ pulumi import sendgrid:index/unsubscribeGroup:UnsubscribeGroup general 12345
 * ```
 *
 * You can find unsubscribe group IDs in the SendGrid dashboard under Settings > Unsubscribe Groups
 * Or use the SendGrid API to list existing groups
 */
export class UnsubscribeGroup extends pulumi.CustomResource {
    /**
     * Get an existing UnsubscribeGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UnsubscribeGroupState, opts?: pulumi.CustomResourceOptions): UnsubscribeGroup {
        return new UnsubscribeGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/unsubscribeGroup:UnsubscribeGroup';

    /**
     * Returns true if the given object is an instance of UnsubscribeGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UnsubscribeGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UnsubscribeGroup.__pulumiType;
    }

    /**
     * The description of the unsubscribe group
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Should this unsubscribe group be used as the default group?
     */
    declare public readonly isDefault: pulumi.Output<boolean | undefined>;
    /**
     * The name you will use to describe this unsubscribe group.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The number of unsubscribes that belong to the group.
     */
    declare public /*out*/ readonly unsubscribes: pulumi.Output<number>;

    /**
     * Create a UnsubscribeGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: UnsubscribeGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UnsubscribeGroupArgs | UnsubscribeGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UnsubscribeGroupState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["name"] = state?.name;
            resourceInputs["unsubscribes"] = state?.unsubscribes;
        } else {
            const args = argsOrState as UnsubscribeGroupArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["isDefault"] = args?.isDefault;
            resourceInputs["name"] = args?.name;
            resourceInputs["unsubscribes"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UnsubscribeGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UnsubscribeGroup resources.
 */
export interface UnsubscribeGroupState {
    /**
     * The description of the unsubscribe group
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Should this unsubscribe group be used as the default group?
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The name you will use to describe this unsubscribe group.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The number of unsubscribes that belong to the group.
     */
    unsubscribes?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a UnsubscribeGroup resource.
 */
export interface UnsubscribeGroupArgs {
    /**
     * The description of the unsubscribe group
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Should this unsubscribe group be used as the default group?
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The name you will use to describe this unsubscribe group.
     */
    name?: pulumi.Input<string | undefined>;
}
