// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class WebhookSecurityPolicy extends pulumi.CustomResource {
    /**
     * Get an existing WebhookSecurityPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookSecurityPolicyState, opts?: pulumi.CustomResourceOptions): WebhookSecurityPolicy {
        return new WebhookSecurityPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index/webhookSecurityPolicy:WebhookSecurityPolicy';

    /**
     * Returns true if the given object is an instance of WebhookSecurityPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WebhookSecurityPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebhookSecurityPolicy.__pulumiType;
    }

    /**
     * The name of the webhook security policy.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * OAuth configuration for webhook authentication. Can be used together with signature.
     */
    declare public readonly oauth: pulumi.Output<outputs.WebhookSecurityPolicyOauth | undefined>;
    /**
     * Signature configuration for webhook authentication. Can be used together with oauth.
     */
    declare public readonly signature: pulumi.Output<outputs.WebhookSecurityPolicySignature | undefined>;

    /**
     * Create a WebhookSecurityPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WebhookSecurityPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookSecurityPolicyArgs | WebhookSecurityPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookSecurityPolicyState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["oauth"] = state?.oauth;
            resourceInputs["signature"] = state?.signature;
        } else {
            const args = argsOrState as WebhookSecurityPolicyArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["oauth"] = args?.oauth;
            resourceInputs["signature"] = args?.signature;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WebhookSecurityPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WebhookSecurityPolicy resources.
 */
export interface WebhookSecurityPolicyState {
    /**
     * The name of the webhook security policy.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * OAuth configuration for webhook authentication. Can be used together with signature.
     */
    oauth?: pulumi.Input<inputs.WebhookSecurityPolicyOauth | undefined>;
    /**
     * Signature configuration for webhook authentication. Can be used together with oauth.
     */
    signature?: pulumi.Input<inputs.WebhookSecurityPolicySignature | undefined>;
}

/**
 * The set of arguments for constructing a WebhookSecurityPolicy resource.
 */
export interface WebhookSecurityPolicyArgs {
    /**
     * The name of the webhook security policy.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * OAuth configuration for webhook authentication. Can be used together with signature.
     */
    oauth?: pulumi.Input<inputs.WebhookSecurityPolicyOauth | undefined>;
    /**
     * Signature configuration for webhook authentication. Can be used together with oauth.
     */
    signature?: pulumi.Input<inputs.WebhookSecurityPolicySignature | undefined>;
}
